apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy after image catalog
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.26.0
      helm:
        valueFiles:
          - $values-repo/cloudnative-pg-operator/values.yaml
    - repoURL: https://github.com/padminisys/cloudnative-pg-ops.git
      targetRevision: main
      ref: values-repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: padmini-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
