apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-db-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after certificates
spec:
  project: default
  source:
    repoURL: https://github.com/padminisys/cloudnative-pg-ops.git
    targetRevision: main
    path: mini-db
    directory:
      include: "postgresql-*.yaml"  # Include cluster and service files only
      exclude: "certificates/*"     # Exclude certificates directory
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: padmini-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
