apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: standalone-postgresql
  namespace: padmini-pg
spec:
  postgresVersion: 15
  instances: 1
  
  # SSL/TLS Configuration using cert-manager
  certificates:
    serverTLSSecret: postgresql-tls-secret
    serverCASecret: postgresql-tls-secret
    clientCASecret: postgresql-tls-secret
    replicationTLSSecret: postgresql-tls-secret
  
  storage:
    size: 10Gi
  
  bootstrap:
    initdb:
      database: myapp_db
      owner: app_user
      secret:
        name: postgresql-credentials
  
  postgresql:
    parameters:
      # SSL Configuration - these paths are automatically managed by the operator
      ssl: "on"
      ssl_cert_file: "/controller/certificates/server-cert.pem"
      ssl_key_file: "/controller/certificates/server-key.pem" 
      ssl_ca_file: "/controller/certificates/ca-cert.pem"
      ssl_crl_file: ""
      ssl_min_protocol_version: "TLSv1.2"
      ssl_ciphers: "ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:!aNULL:!MD5:!DSS"
      ssl_prefer_server_ciphers: "on"
      log_connections: "on"
      log_disconnections: "on"
      max_connections: "100"
      shared_buffers: "128MB"
  
  monitoring:
    enabled: true
  
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi