apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgresql-tls-cert
  namespace: padmini-pg
spec:
  secretName: postgresql-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - postgresql.padmini.systems
  usages:
    - digital signature
    - key encipherment
    - server auth
  duration: 2160h
  renewBefore: 360h
  subject:
    organizationalUnits:
      - "PostgreSQL Database"
    organizations:
      - "Padmini Systems"
  privateKey:
    algorithm: RSA
    size: 2048