apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: standalone-postgresql
  namespace: padmini-pg
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  instances: 1

  certificates:
    serverTLSSecret: postgresql-tls-secret
    serverCASecret: postgresql-tls-secret
    clientCASecret: postgresql-tls-secret
    replicationTLSSecret: postgresql-tls-secret

  storage:
    size: 10Gi
    storageClass: ceph-filesystem

  bootstrap:
    initdb:
      database: k8s_db
      owner: app_user
      secret:
        name: postgresql-credentials

  postgresql:
    parameters:
      # Do not set 'ssl' when certificates are used, CloudNativePG manages it automatically
      ssl_min_protocol_version: TLSv1.2
      ssl_ciphers: ECDHE+AESGCM:ECDHE+CHACHA20:DHE+AESGCM:DHE+CHACHA20:!aNULL:!MD5:!DSS
      ssl_prefer_server_ciphers: true         # boolean
      log_connections: true                   # boolean
      log_disconnections: true                # boolean
      max_connections: 100                    # integer is preferred, but string also works
      shared_buffers: 128MB                   # string as per PostgreSQL format

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
