apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgresql-image-catalog
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  # Remote ClusterImageCatalog from CloudNativePG repository
  - https://raw.githubusercontent.com/cloudnative-pg/postgres-containers/main/Debian/ClusterImageCatalog-bookworm.yaml

patchesStrategicMerge:
  - image-catalog-patch.yaml
