name: Deploy CloudNativePG Stack

on:
  push:
    branches: [main]
    paths:
      - 'argocd-apps/**'
      - 'cloudnative-pg-operator/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.PSYS_CENTOS_1_KUBE_CONFIG }}" | base64 -d > /tmp/kubeconfig
          chmod 600 /tmp/kubeconfig
        env:
          KUBECONFIG: /tmp/kubeconfig

      - name: Deploy PostgreSQL Image Catalog
        run: kubectl apply -f argocd-apps/postgresql-image-catalog.yaml
        env:
          KUBECONFIG: /tmp/kubeconfig

      - name: Wait for Image Catalog Sync
        run: sleep 30
        
      - name: Deploy CloudNativePG Operator
        run: kubectl apply -f argocd-apps/cloudnative-pg-operator.yaml
        env:
          KUBECONFIG: /tmp/kubeconfig 